name: product_assessment
description: Product Assessment.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mockito: ^5.4.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  bloc: ^8.1.2
  dio: ^5.3.2
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/graphik_font/GraphikRegular.otf
        - asset: assets/fonts/graphik_font/GraphikRegularItalic.otf
          style: italic
        - asset: assets/fonts/graphik_font/GraphikMedium.otf
          weight: 500
        - asset: assets/fonts/graphik_font/GraphikSemibold.otf
          weight: 600
        - asset: assets/fonts/graphik_font/GraphikBold.otf
          weight: 700
